baseURL ="/"
languageCode = "en-us"
title = "Stephanie Orellana"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-180361884-1"

#Uncomment below to enable syntax highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
#See https://xyproto.github.io/splash/docs/all.html for more styles
pygmentsStyle = "paraiso-dark"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:year/:month/:day/:slug/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Inicio"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Sobre mí"
    pre = "smile"
    url = "/about/"
    weight = 2
  [[menu.nav]]
    name = "Blog"
    pre = "edit"
    url = "/post/"
    weight = 3
  [[menu.nav]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 4
  [[menu.nav]]
    name = "Proyectos"
    pre = "codepen"
    url = "/projects2/"
    weight = 5


[params]
  includeBootstrapJs = true
  showActiveNav = true
  containerMaxWidth = "1200px"
  dateFormat = "Jan 2, 2006"
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false
  
[Params.social.share]
  facebook = true
  linkedin = true
  twitter = true
  whatsapp = false
  email = false
